# Generated by Django 4.1.5 on 2023-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='assets',
            field=models.ManyToManyField(related_name='articles',
                                         to='equity_eye.asset'),
        ),
    ]
